### ISSUE TITLE
Strange issue with chrome headless

### ISSUE THREAD

**Issue by samstickland** [rosenfeld/rspec_nested_transactions#3]
Hi,

I have a strange issue where `rspec_nested_transactions` causes feature tests ran with chrome headless (selenium) to hang. This is my configuration, and as you can see nested transactions are not used for feature tests:

```
   config.nested_transaction do |example_or_group, run|
     (run[] && next) if example_or_group.metadata[:type] == :feature

     ActiveRecord::Base.transaction(requires_new: true) do
       run[]
       raise ActiveRecord::Rollback
     end
   end
```

These feature tests work with capybara-webkit, so this seems pretty strange to me. The tests hang on the `run[] && next` statement.

**Comment by samstickland** [comment]
Sorry, false alarm. Somewhere along the line I'd also changed `(run[]; next)` to `(run[] && next)` which was the cause of the problem

**Comment by rosenfeld** [comment]
Glad you figured it out :-)
